<?php
/**
 * @var Magenest\Bt1\Block\ItemPending $block;
 */
?>


<div>
    <h2><strong>Show Magenest Rules Information</strong></h2>
    <table border="1">
        <thead>
        <tr>
            <th><strong>ID</strong></th>
            <th><strong>Title</strong></th>
            <th><strong>Status</strong></th>
            <th><strong>Rule Type</strong></th>
            <th><strong>Created At</strong></th>
            <th><strong>Updated At</strong></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getRuleStatusPending() as $item) :?>
            <tr>
                <td><?php echo $item->getId()?></td>
                <td><?php echo $item->getTitle()?></td>
                <td><?php echo $item->getStatus()?></td>
                <td><?php echo $item->getRuleType()?></td>
                <td><?php echo $item->getCreatedAt()?></td>
                <td><?php echo $item->getUpdatedAt()?></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
