<?php


namespace Magenest\Test\Model\ResourceModel\Gift;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName='id';
    protected function _construct()
    {
        $this->_init('Magenest\Test\Model\Gift','Magenest\Test\Model\ResourceModel\Gift');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
