<!--<div>-->
<!--    <label>Bạn sẽ nhận được điểm thương khi bạn đăng kí tài khoản vào hệ thống</label>-->
<!--</div>-->

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magenest\Test\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?= $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?></p>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
                </div>
            </div>
        </div>
        <div class="block-title" style="margin-top: 30px">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Reward Points')) ?></strong>
        </div>
        <div class="block-content1" aria-labelledby="block-new-customer-heading">
            <p><?= $block->escapeHtml(__('Bạn sẽ nhận được 50 điểm thưởng khi bạn đăng kí tài khoản vào hệ thống')) ?></p>
        </div>
    </div>

<?php endif; ?>

