<?php


namespace Magenest\Test\Model\ResourceModel\HistoryPoint;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName="id";
    protected function _construct()
    {
        $this->_init('Magenest\Test\Model\HistoryPoint', 'Magenest\Test\Model\ResourceModel\HistoryPoint');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
