<?php


namespace Magenest\Bt1\Model\ResourceModel\Rule;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init('Magenest\Bt1\Model\Rule','Magenest\Bt1\Model\ResourceModel\Rule');
        parent::_construct(); // TODO: Change the autogenerated stub
    }
    public function getItems()
    {
        return $this->addFieldToSelect('*')
            ->addFieldToFilter('status','pending');
    }
}
